export const QUERY_KEYS = {
  AUTH_ME: ['auth', 'me'],
  USERS: ['users'],
  USER: (id: string) => ['users', id],
  CLIENTS: ['clients'],
  CLIENT: (id: string) => ['clients', id],
  SECTEURS: ['secteurs'],
  PRODUITS: ['produits'],
  FACTURES: ['factures'],
  FACTURE: (id: string) => ['factures', id],
  PAIEMENTS: ['paiements'],
  PAIEMENT: (id: string) => ['paiements', id],
  DASHBOARD_KPIS: ['dashboard', 'kpis'],
  DASHBOARD_REVENUE: (year: number) => ['dashboard', 'revenue', year],
  DASHBOARD_STATUS: ['dashboard', 'status'],
  DASHBOARD_TOP_CLIENTS: ['dashboard', 'top-clients'],
  NOTIFICATIONS: ['notifications'],
  NOTIFICATIONS_COUNT: ['notifications', 'count'],
  REPORTS_REVENUE: ['reports', 'revenue'],
  REPORTS_IMPAYES: ['reports', 'impayes'],
} as const;
