export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  CLIENTS: '/clients',
  CLIENT_DETAIL: '/clients/:id',
  PRODUITS: '/produits',
  FACTURES: '/factures',
  FACTURE_CREATE: '/factures/nouvelle',
  FACTURE_EDIT: '/factures/:id/modifier',
  FACTURE_DETAIL: '/factures/:id',
  PAIEMENTS: '/paiements',
  USERS: '/utilisateurs',
  REPORTS: '/rapports',
  SECTEURS: '/secteurs',
  COMPANY_SETTINGS: '/parametres/societe',
  // SuperAdmin
  SUPERADMIN: '/superadmin',
  SUPERADMIN_SOCIETES: '/superadmin/societes',
  SUPERADMIN_SOCIETE_CREATE: '/superadmin/societes/nouvelle',
  SUPERADMIN_SOCIETE_DETAIL: '/superadmin/societes/:id',
} as const;
